---

- name: etckeeperインストール
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - etckeeper

- name: gitconfig
  template: src=gitconfig.j2 dest=/root/.gitconfig owner=root group=root mode=0644
