---

- name: etckeeperインストール
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - etckeeper

- name: etckeeper設定
  copy: src=etckeeper.conf dest=/etc/etckeeper/etckeeper.conf

#- name: gitconfig存在確認
#  shell: test -e /root/.gitconfig
#  register: result
#  changed_when: result.rc != 0
#  failed_when: result.rc not in [0, 1]
#
#- name: git config設定
#  template: src=gitconfig.j2 dest=/root/.gitconfig
#  when: result.rc != 0
#
#- name: etckeeper 1st commit
#  shell: etckeeper init && etckeeper commit -m 1st creates=/etc/.git chdir=/etc
#
