---

- name: apt-get update
  action: apt update_cache=yes cache_valid_time=86400

- name: hostname設定
  hostname: name={{ common_server_host_name }}

- include: etckeeper.yml
  when: common_etckeeper_install == true

- include: locale.yml
  when: common_locale_setting == true

- include: timezone.yml
  when: common_timezone_setting == true
